"use client";
import { useEffect, useState } from "react";
import type { WalletAccountV6 } from "starknet";
import { connectWallet, disconnectWallet, getWalletSession, getWalletStore, getWallets, restoreWallet, shorten, subscribeWalletSession, type DiscoveredWallet } from "@/lib/wallet";
export default function WalletButton({ onAccount }: { onAccount?: (account: WalletAccountV6) => void }) {
  const [wallets, setWallets] = useState<DiscoveredWallet[]>([]); const [account, setAccount] = useState<WalletAccountV6 | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { const store = getWalletStore(); setWallets(store.getWallets()); const sync = () => setAccount(getWalletSession()?.account ?? null); sync(); restoreWallet().then((restored) => restored && setAccount(restored)); const unsubscribe = subscribeWalletSession(sync); return () => { store.subscribe(() => setWallets(store.getWallets())); unsubscribe(); }; }, []);
  async function choose(wallet: DiscoveredWallet) { setBusy(true); setError(""); try { const next = await connectWallet(wallet); setAccount(next); onAccount?.(next); } catch (err) { setError(err instanceof Error ? err.message : "Wallet connection failed."); } finally { setBusy(false); } }
  if (account) return <div className="flex items-center gap-2"><span className="mono rounded-full border border-[var(--border)] bg-white px-4 py-2 text-xs">{shorten(account.address)}</span><button aria-label="Disconnect wallet" title="Disconnect wallet" onClick={() => disconnectWallet()} className="grid h-8 w-8 place-items-center rounded-full border border-[var(--border)] bg-white text-sm hover:border-[var(--ink)]">⏻</button></div>;
  return <div className="relative"><button className="rounded-full bg-[var(--ink)] px-5 py-3 text-sm font-medium text-white transition hover:bg-[var(--forest)] disabled:opacity-50" disabled={busy} onClick={() => wallets[0] && choose(wallets[0])}>{busy ? "Connecting…" : wallets.length ? "Connect wallet" : "Find wallet"}</button>{wallets.length > 1 && <div className="mt-2 flex gap-2">{wallets.slice(1).map((wallet, index) => <button key={`${wallet.name}-${index}`} onClick={() => choose(wallet)} className="text-xs underline">{wallet.name}</button>)}</div>}{error && <p className="absolute right-0 top-12 w-64 rounded border border-red-200 bg-red-50 p-2 text-xs text-red-800">{error}</p>}</div>;
}
